#!/bin/bash
set -e
if [ -f ~/.XCompose ]; then
	cat <<'EOF' >&2
You already have a `~/.XCompose`.  Move it out of the way.

You may want to merge it into this file, taking care to avoid
duplicates.

Kragen Javier Sitaker <kragen@canonical.org>

EOF
	exit 1
fi
personal=~/.config/XCompose
touch $personal
(
	echo "include \"%L\""
	for x in dotXCompose $@
	do
		echo "include \"$(realpath ./$x)\""
	done
    echo "include \"$personal\""
) > ~/.XCompose
